# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'streak_mobile' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for streak_mobile
  pod 'Firebase/Core'

  target 'streak_mobile-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'streak_mobileTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'streak_mobile-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

end
